logging:
    level:
        com:
            google:
                mapper: debug
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.bdqn.entity
server:
    port: 8090
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    tomcat:
        uri-encoding: UTF-8
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/itripdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
    redis:
        host: 127.0.0.1
        password: 123456
        port: 6379
        timeout: 3000
        client-type: jedis
#        username: root
